/**
 * Fetches model pricing from the LiteLLM model_prices_and_context_window.json
 * and generates src/lib/pricing.ts.
 *
 * Usage:
 *   npx tsx scripts/generate-pricing.ts
 */

import { writeFileSync } from "fs";
import { join } from "path";

const LITELLM_URL =
  "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json";

// Providers toongate routes to (excludes vertex_ai sub-variants to keep table lean)
const PROVIDER_WHITELIST = new Set([
  "openai",
  "text-completion-openai",
  "anthropic",
  "gemini",
  "mistral",
  "cohere_chat",
  "groq",
  "deepseek",
]);

const VALID_MODES = new Set(["chat", "completion", "embedding", ""]);

interface LiteLLMEntry {
  litellm_provider?: string;
  mode?: string;
  input_cost_per_token?: number;
}

interface PricingEntry {
  /** Input cost in USD per million tokens */
  input: number;
  provider: string;
}

async function main() {
  console.log("Fetching LiteLLM pricing data...");
  const res = await fetch(LITELLM_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);

  const data = (await res.json()) as Record<string, LiteLLMEntry>;

  const pricing: Record<string, PricingEntry> = {};

  for (const [model, info] of Object.entries(data)) {
    if (model === "sample_spec") continue;

    const provider = info.litellm_provider ?? "";
    const mode = info.mode ?? "";
    const inputCostPerToken = info.input_cost_per_token;

    if (!PROVIDER_WHITELIST.has(provider)) continue;
    if (!VALID_MODES.has(mode)) continue;
    if (inputCostPerToken == null || inputCostPerToken === 0) continue;

    pricing[model] = {
      input: Math.round(inputCostPerToken * 1_000_000 * 1_000_000) / 1_000_000,
      provider,
    };
  }

  const sorted = Object.entries(pricing).sort(([a], [b]) => a.localeCompare(b));
  const totalModels = sorted.length;

  // Build the TypeScript source
  const priceLines = sorted
    .map(([model, { input }]) => `  "${model}": ${input},`)
    .join("\n");

  const now = new Date().toISOString().slice(0, 10);

  const source = `// Generated by scripts/generate-pricing.ts — do not edit manually.
// Source: ${LITELLM_URL}
// Generated: ${now} — ${totalModels} models

// Input cost in USD per million tokens, keyed by model name as returned by the provider.
// Used only to estimate USD saved from token compression — slight inaccuracies are acceptable.
const MODEL_PRICES: Record<string, number> = {
${priceLines}
};

// Fallback: gpt-4o list price as a reasonable mid-tier default
const DEFAULT_PRICE_PER_MILLION = 2.5;

export function calcUsdSaved(model: string, tokensSaved: number): number {
  const pricePerMillion = MODEL_PRICES[model] ?? DEFAULT_PRICE_PER_MILLION;
  return (tokensSaved / 1_000_000) * pricePerMillion;
}
`;

  const outPath = join(import.meta.dirname, "../src/lib/pricing.ts");
  writeFileSync(outPath, source, "utf-8");
  console.log(`✓ Wrote ${totalModels} models to src/lib/pricing.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
