// Generated by Wrangler by running `wrangler types src/worker.d.ts`

interface Env {
  UPSTREAM_URL: string;
  OPENAI_API_KEY: string;
  ANTHROPIC_API_KEY: string;
  // Azure OpenAI — set via `wrangler secret put`
  AZURE_OPENAI_API_KEY: string;
  AZURE_OPENAI_ENDPOINT: string;    // e.g. https://{resource}.openai.azure.com
  AZURE_OPENAI_API_VERSION: string; // default: 2024-02-01
  // Gemini — set via `wrangler secret put`
  GEMINI_API_KEY: string;
  GEMINI_UPSTREAM_URL: string;      // override for Vertex AI; default: https://generativelanguage.googleapis.com/v1beta/openai
  // DeepSeek — set via `wrangler secret put`
  DEEPSEEK_API_KEY: string;
  DEEPSEEK_UPSTREAM_URL: string;    // override; default: https://api.deepseek.com
  TOON_THRESHOLD: string;
  TOON_THRESHOLD_MESSAGES: string;
  TOON_THRESHOLD_CHAT: string;
  TOON_THRESHOLD_EMBEDDINGS: string;
  TOON_LOG_SAVINGS: string;
  TOON_DRY_RUN: string;
  UPSTREAM_TIMEOUT_MS: string;
  DB: D1Database;
  CF_AIG_TOKEN: string;
  ADMIN_KEY: string;
  PROXY_AUTH_KEY: string;
  // Optional — POST savings event as JSON after each request (Slack/Discord/custom webhook).
  SAVINGS_WEBHOOK_URL?: string;
  // Adaptive threshold — set "true" to auto-tune TOON_THRESHOLD from savings history.
  TOON_THRESHOLD_AUTO?: string;
  // Per-field exclusion — comma-separated fields to strip before TOON encoding, e.g. "id,ts".
  TOON_EXCLUDE_FIELDS?: string;
  // AWS Bedrock — set via `wrangler secret put`
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  AWS_REGION?: string;           // default: us-east-1
  AWS_SESSION_TOKEN?: string;    // optional, for temporary credentials
  // Vertex AI native — set via `wrangler secret put`
  VERTEX_PROJECT?: string;       // GCP project ID
  VERTEX_LOCATION?: string;      // default: us-central1
  VERTEX_ACCESS_TOKEN?: string;  // short-lived OAuth2 access token
  // Optional — configure via `rate_limits` binding in wrangler.jsonc.
  // When unset, rate limiting is skipped gracefully.
  RATE_LIMITER?: RateLimit;
}
