// Generated by Wrangler by running `wrangler types src/worker.d.ts`

interface Env {
  UPSTREAM_URL: string;
  OPENAI_API_KEY: string;
  ANTHROPIC_API_KEY: string;
  // Azure OpenAI — set via `wrangler secret put`
  AZURE_OPENAI_API_KEY: string;
  AZURE_OPENAI_ENDPOINT: string;    // e.g. https://{resource}.openai.azure.com
  AZURE_OPENAI_API_VERSION: string; // default: 2024-02-01
  // Gemini — set via `wrangler secret put`
  GEMINI_API_KEY: string;
  GEMINI_UPSTREAM_URL: string;      // override for Vertex AI; default: https://generativelanguage.googleapis.com/v1beta/openai
  // DeepSeek — set via `wrangler secret put`
  DEEPSEEK_API_KEY: string;
  DEEPSEEK_UPSTREAM_URL: string;    // override; default: https://api.deepseek.com
  TOON_THRESHOLD: string;
  TOON_THRESHOLD_MESSAGES: string;
  TOON_THRESHOLD_CHAT: string;
  TOON_THRESHOLD_EMBEDDINGS: string;
  TOON_LOG_SAVINGS: string;
  TOON_DRY_RUN: string;
  UPSTREAM_TIMEOUT_MS: string;
  DB: D1Database;
  CF_AIG_TOKEN: string;
  ADMIN_KEY: string;
  PROXY_AUTH_KEY: string;
  // Optional — configure via `rate_limits` binding in wrangler.jsonc.
  // When unset, rate limiting is skipped gracefully.
  RATE_LIMITER?: RateLimit;
}
