// Generated by Wrangler by running `wrangler types src/worker.d.ts`

interface Env {
  UPSTREAM_URL: string;
  OPENAI_API_KEY: string;
  ANTHROPIC_API_KEY: string;
  TOON_THRESHOLD: string;
  TOON_LOG_SAVINGS: string;
  DB: D1Database;
}
